{% set version = "1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jsonlite
  version: {{ version }}

source:
  fn: jsonlite_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/jsonlite_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/jsonlite/jsonlite_{{ version }}.tar.gz
  sha256: 6490371082a387cb1834048ad8cdecacb8b6b6643751b50298c741490c798e02

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]
  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - R -e "library('jsonlite')"  # [not win]
    - R -e \"library('jsonlite')\"  # [win]

about:
  home: http://arxiv.org/abs/1403.2805, https://www.opencpu.org/posts/jsonlite-a-smarter-json-encoder
  license: MIT
  license_file: LICENSE
  summary: "A fast JSON parser and generator optimized for statistical data and the web. Started
    out as a fork of 'RJSONIO', but has been completely rewritten in recent versions.
    The package offers flexible, robust, high performance tools for working with JSON
    in R and is particularly powerful for building pipelines and interacting with a
    web API. The implementation is based on the mapping described in the vignette (Ooms,
    2014). In addition to converting JSON data from/to R objects, 'jsonlite' contains
    functions to stream, validate, and prettify JSON data. The unit tests included with
    the package verify that all edge cases are encoded and decoded consistently for
    use with dynamic data in systems and applications."

extra:
  recipe-maintainers:
    - ocefpaf
    - bgruening
